openapi: 3.0.3
info:
   title: Inditex API
   version: '1.0'
   description: Información de stock de Inditex
   contact:
      name: Carlos Diaz
      email: cdr8725@gmail.com
paths:
   /prices/{brandId}/{productId}:
      get:
         summary: Obtener la tarifa a aplicar por ID de empresa, producto y fecha que se desea consultar.
         description: Obtener la tarifa a aplicar teniendo en cuenta el ID de la empresa del grupo, el id del producto y la
            fecha que nos interesa.
         tags:
         - Prices
         operationId: obtenerTarifaAplicar
         parameters:
         -  in: path
            name: brandId
            description: ID de la tienda dentro del grupo Inditex
            required: true
            schema:
               type: string
         -  in: path
            name: productId
            description: ID del producto buscado
            required: true
            schema:
               type: string
         -  in: query
            name: fechaAConsultar
            description: Fecha que queremos consultar
            required: true
            schema:
               type: string
               format: date-time
         responses:
            '200':
               description: OK
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/PriceDTO'
            '204':
               description: No encontrado
            '400':
               description: Error en la url
            '500':
               description: BD no accesible
components:
   schemas:
      PriceDTO:
         type: object
         properties:
            brandId:
               type: string
               example: '1'
            productID:
               type: string
               example: '1565'
            priceList:
               type: string
               example: '3'
            consultationDate:
               type: string
               format: date-time
               example: '2023-05-01T14:30:00Z'
            priority:
               type: integer
               example: 1
            precio:
               type: number
               example: 19.99
            curr:
               type: string
               example: EUR